version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - /Users/sergejlapin/Projects/FASTAPI/workmate_test_assignment:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
